include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  errors:
    missing_return: error
    missing_required_param: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - avoid_print
    - always_declare_return_types
    - annotate_overrides
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_build_context_synchronously
    - cancel_subscriptions
    - close_sinks
    - always_use_package_imports
    - avoid_relative_lib_imports
    - avoid_dynamic_calls
    - avoid_returning_null_for_void
    - prefer_const_constructors_in_immutables
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_null_aware_assignments
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_lambdas
    - unnecessary_this
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - use_string_buffers
    - unawaited_futures
    - discarded_futures
