---
- import_tasks: validate.yml

- import_tasks: install.yml
  when: alloy_agent_action == 'deploy'

- import_tasks: deploy.yml
  when: alloy_agent_action == 'deploy'

- import_tasks: verify.yml
  when: alloy_agent_action == 'verify'

- import_tasks: rollback.yml
  when: alloy_agent_action == 'rollback'

