import { locales } from '@/i18n/config';

export const SUPPORTED_CURRENCIES = [
  'USD',
  'RUB',
  'EUR',
  'CNY',
  'INR',
  'IDR',
  'VND',
  'THB',
  'JPY',
  'KRW',
  'SAR',
  'IRR',
  'TRY',
  'PKR',
  'BDT',
  'MYR',
  'KZT',
  'BYN',
  'MMK',
  'UZS',
  'NGN',
  'IQD',
  'ETB',
  'TMT',
  'TWD',
  'ILS',
  'PLN',
  'PHP',
  'UAH',
  'CZK',
  'RON',
  'HUF',
  'SEK',
] as const;

export type SupportedCurrency = (typeof SUPPORTED_CURRENCIES)[number];

export const CURRENCY_STORAGE_KEY = 'cybervpn.currency';
export const CURRENCY_COOKIE_NAME = 'cybervpn_currency';
export const CURRENCY_CHANGE_EVENT = 'cybervpn:currency-change';

export const LOCALE_DEFAULT_CURRENCY: Record<(typeof locales)[number], SupportedCurrency> = {
  'en-EN': 'USD',
  'ru-RU': 'RUB',
  'zh-CN': 'CNY',
  'hi-IN': 'INR',
  'id-ID': 'IDR',
  'vi-VN': 'VND',
  'th-TH': 'THB',
  'ja-JP': 'JPY',
  'ko-KR': 'KRW',
  'ar-SA': 'SAR',
  'fa-IR': 'IRR',
  'tr-TR': 'TRY',
  'ur-PK': 'PKR',
  'bn-BD': 'BDT',
  'ms-MY': 'MYR',
  'es-ES': 'EUR',
  'kk-KZ': 'KZT',
  'be-BY': 'BYN',
  'my-MM': 'MMK',
  'uz-UZ': 'UZS',
  'ha-NG': 'NGN',
  'yo-NG': 'NGN',
  'ku-IQ': 'IQD',
  'am-ET': 'ETB',
  'fr-FR': 'EUR',
  'tk-TM': 'TMT',
  'zh-Hant': 'TWD',
  'he-IL': 'ILS',
  'de-DE': 'EUR',
  'pt-PT': 'EUR',
  'it-IT': 'EUR',
  'nl-NL': 'EUR',
  'pl-PL': 'PLN',
  'fil-PH': 'PHP',
  'uk-UA': 'UAH',
  'cs-CZ': 'CZK',
  'ro-RO': 'RON',
  'hu-HU': 'HUF',
  'sv-SE': 'SEK',
};

export const CURRENCY_LABELS: Record<SupportedCurrency, string> = {
  USD: 'US Dollar',
  RUB: 'Russian Ruble',
  EUR: 'Euro',
  CNY: 'Chinese Yuan',
  INR: 'Indian Rupee',
  IDR: 'Indonesian Rupiah',
  VND: 'Vietnamese Dong',
  THB: 'Thai Baht',
  JPY: 'Japanese Yen',
  KRW: 'South Korean Won',
  SAR: 'Saudi Riyal',
  IRR: 'Iranian Rial',
  TRY: 'Turkish Lira',
  PKR: 'Pakistani Rupee',
  BDT: 'Bangladeshi Taka',
  MYR: 'Malaysian Ringgit',
  KZT: 'Kazakhstani Tenge',
  BYN: 'Belarusian Ruble',
  MMK: 'Myanmar Kyat',
  UZS: 'Uzbekistani Som',
  NGN: 'Nigerian Naira',
  IQD: 'Iraqi Dinar',
  ETB: 'Ethiopian Birr',
  TMT: 'Turkmenistan Manat',
  TWD: 'New Taiwan Dollar',
  ILS: 'Israeli Shekel',
  PLN: 'Polish Zloty',
  PHP: 'Philippine Peso',
  UAH: 'Ukrainian Hryvnia',
  CZK: 'Czech Koruna',
  RON: 'Romanian Leu',
  HUF: 'Hungarian Forint',
  SEK: 'Swedish Krona',
};

export function isSupportedCurrency(value: unknown): value is SupportedCurrency {
  return typeof value === 'string' && SUPPORTED_CURRENCIES.includes(value as SupportedCurrency);
}

export function getDefaultCurrencyForLocale(locale: string): SupportedCurrency {
  return LOCALE_DEFAULT_CURRENCY[locale as keyof typeof LOCALE_DEFAULT_CURRENCY] ?? 'USD';
}
