import { PARTNER_NAV_ITEMS } from '@/features/partner-shell/config/section-registry';

export const DASHBOARD_NAV_ITEMS = PARTNER_NAV_ITEMS;

export const dashboardNavigationItems = DASHBOARD_NAV_ITEMS;

export const DASHBOARD_NAV_LABEL_FALLBACKS = {
  adminConsole: 'PARTNER PORTAL',
  analytics: 'ANALYTICS',
  analyticsHint: 'Performance, exports, explainability',
  application: 'APPLICATION',
  applicationHint: 'Onboarding, review, requested info',
  campaigns: 'CAMPAIGNS',
  campaignsHint: 'Assets, enablement, approvals',
  cases: 'SUPPORT & CASES',
  casesHint: 'Messages, disputes, requests',
  closeMenu: 'Close menu',
  codes: 'CODES & TRACKING',
  codesHint: 'Links, QR, attribution setup',
  compliance: 'COMPLIANCE',
  complianceHint: 'Declarations, policy, governance',
  conversions: 'CONVERSIONS',
  conversionsHint: 'Orders, leads, commission context',
  dashboard: 'DASHBOARD',
  dashboardHint: 'Status, tasks, portal readiness',
  finance: 'FINANCE',
  financeHint: 'Statements, payout readiness, holds',
  badgeLimited: 'LIMITED',
  badgeLocked: 'LOCKED',
  badgeReadOnly: 'READ ONLY',
  badgeTask: 'ACTION',
  groupControl: 'Control & Support',
  groupControlHint: 'Compliance tasks, disputes, requested info',
  groupFinance: 'Finance',
  groupFinanceHint: 'Statements, payout readiness, holds',
  groupMain: 'Overview',
  groupMainHint: 'Current posture, alerts, urgent actions',
  groupOnboarding: 'Start',
  groupOnboardingHint: 'Application, organization, contracts',
  groupPromotion: 'Programs & Promotion',
  groupPromotionHint: 'Lanes, links, campaigns',
  groupResults: 'Results',
  groupResultsHint: 'Orders, attribution, exports',
  groupTechnical: 'Integrations',
  groupTechnicalHint: 'Tokens, postbacks, reseller tools',
  groupWorkspace: 'Workspace',
  groupWorkspaceHint: 'People, settings, workspace security',
  integrations: 'INTEGRATIONS',
  integrationsHint: 'Tokens, postbacks, delivery logs',
  legal: 'CONTRACTS & LEGAL',
  legalHint: 'Terms, policies, acceptance history',
  mainNavigation: 'Main navigation',
  notifications: 'INBOX',
  notificationsHint: 'Status changes and alerts',
  openMenu: 'Open menu',
  organization: 'ORGANIZATION',
  organizationHint: 'Business profile, domains, contacts',
  programs: 'PROGRAMS',
  programsHint: 'Lanes, restrictions, approvals',
  reseller: 'RESELLER CONSOLE',
  resellerHint: 'Storefront and distribution scope',
  secureSession: 'SECURE SESSION',
  settings: 'SETTINGS',
  settingsHint: 'MFA, sessions, preferences',
  sidebar: 'Sidebar',
  team: 'TEAM & ACCESS',
  teamHint: 'Members, roles, workspace security',
} as const;
