"""Canonical event families reserved for the partner platform baseline."""

PARTNER_PLATFORM_EVENT_FAMILIES = {
    "growth_code": (
        "growth_code.issued",
        "growth_code.resolved",
        "growth_code.rejected",
        "growth_code.reserved",
        "growth_code.reservation_committed",
        "growth_code.released",
        "growth_code.reservation_expired",
        "growth_code.redeemed",
        "growth_code.revoked",
    ),
    "invite": (
        "invite.generated_from_order",
        "invite.legacy_manual_created",
        "invite.redeemed",
        "invite.owner_reward_created",
        "invite.batch.issued",
        "invite.batch.revoked",
        "invite.batch.extended",
        "invite.batch.resend_requested",
    ),
    "referral": (
        "referral.reward_pending",
        "referral.reward_available",
        "referral.reward_reversed",
    ),
    "promo": (
        "promo.applied_to_order",
        "promo.rejected",
    ),
    "payment": (
        "payment.completed",
        "payment.settlement.unlinked",
        "payment.completed.partner_earning.reconciliation_required",
    ),
    "gift": (
        "gift.issued",
        "gift.redeemed",
        "gift.revoked",
    ),
    "storefront": (
        "storefront.resolved",
        "storefront.binding.changed",
    ),
    "partner_bot": (
        "partner_bot.created",
        "partner_bot.provisioning_requested",
        "partner_bot.status_changed",
    ),
    "partner": (
        "partner.attribution.captured",
        "partner.attribution.claimed",
    ),
    "realm": (
        "realm.session.issued",
        "realm.session.revoked",
    ),
    "privacy_request": (
        "privacy_request.created",
        "privacy_request.existing_returned",
        "privacy_request.review_started",
        "privacy_request.identity_verification_requested",
        "privacy_request.identity_verified",
        "privacy_request.approved",
        "privacy_request.denied",
        "privacy_request.scheduled",
        "privacy_request.fulfillment_started",
        "privacy_request.fulfillment_succeeded",
        "privacy_request.fulfillment_failed",
        "privacy_request.canceled",
    ),
    "order": (
        "order.created",
        "order.finalized",
        "order.refunded",
    ),
    "refund": (
        "refund.status_changed",
        "refund.provider_state_reconciled",
    ),
    "attribution": (
        "attribution.touchpoint.recorded",
        "attribution.result.finalized",
    ),
    "growth_reward": (
        "growth_reward.allocation.created",
        "growth_reward.allocation.available",
        "growth_reward.allocation.reversed",
    ),
    "growth_benefit": ("growth_benefit.fulfillment.completed",),
    "settlement": (
        "settlement.earning.created",
        "settlement.earning.snapshot_incomplete",
        "settlement.earning_hold.released",
        "settlement.statement.generated",
        "settlement.statement.closed",
        "settlement.statement.reopened",
        "settlement.payout_account.created",
        "settlement.payout_account.verified",
        "settlement.payout_account.default_selected",
        "settlement.payout_instruction.created",
        "settlement.payout_instruction.approved",
        "settlement.payout.execution.requested",
        "settlement.payout.execution.submitted",
        "settlement.payout.execution.reconciled",
    ),
    "risk": (
        "risk.review.opened",
        "risk.decision.recorded",
        "risk.review.resolved",
        "risk.evidence.attached",
        "risk.governance_action.recorded",
    ),
    "rollout": (
        "rollout.pilot_cohort.created",
        "rollout.pilot_cohort.activated",
        "rollout.pilot_cohort.paused",
        "rollout.runbook_acknowledged",
        "rollout.rollback_drill.recorded",
        "rollout.go_no_go.recorded",
    ),
    "entitlement": (
        "entitlement.grant.activated",
        "entitlement.grant.revoked",
    ),
    "service_access": (
        "service_access.device_credential.registered",
        "service_access.device_credential.revoked",
        "service_access.delivery_channel.resolved",
        "service_access.delivery_channel.archived",
    ),
    "reporting": (
        "reporting.export.generated",
        "reporting.mart.refreshed",
    ),
}
