---
all:
  children:
    edge_production:
      hosts: {}
    remnawave_edge_production:
      hosts:
        s1-ru-msk-3:
          ansible_host: 178.159.94.225
          ansible_user: root
          ansible_ssh_private_key_file: /home/beep/.ssh/MainKey2_private_fixed.pem
          remnawave_node_remark: "🇷🇺 RU Moscow 01 25G"
          remnawave_edge_secret_key: "{{ vault_remnawave_edge_secret_key_s1_ru_msk_3 }}"
        s1-ru-spb-3:
          ansible_host: 193.233.91.99
          ansible_user: root
          ansible_ssh_private_key_file: /home/beep/.ssh/MainKey2_private_fixed.pem
          remnawave_node_remark: "🇷🇺 RU SPB 01 25G"
          remnawave_edge_secret_key: "{{ vault_remnawave_edge_secret_key_s1_ru_spb_3 }}"
        s1-nl-4:
          ansible_host: 138.16.140.44
          ansible_user: root
          ansible_ssh_private_key_file: /home/beep/.ssh/MainKey2_private_fixed.pem
          remnawave_node_remark: "🇳🇱 NL Amsterdam 01 10G"
          remnawave_edge_secret_key: "{{ vault_remnawave_edge_secret_key_s1_nl_4 }}"
        s1-de-3:
          ansible_host: 138.124.115.206
          ansible_user: root
          ansible_ssh_private_key_file: /home/beep/.ssh/MainKey2_private_fixed.pem
          remnawave_node_remark: "🇩🇪 DE Frankfurt 01 25G"
          remnawave_edge_secret_key: "{{ vault_remnawave_edge_secret_key_s1_de_3 }}"
    helix_edge_production:
      hosts: {}
    control_plane_production:
      hosts: {}
