route:
  receiver: stage1-local-acceptance
  group_by:
    - alertname
    - service
    - stage
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: stage1-local-acceptance
