FROM python:3.13.14-alpine

WORKDIR /app

RUN addgroup -S metrics \
    && adduser -S -D -H -G metrics metrics \
    && pip install --no-cache-dir prometheus-client==0.22.1

COPY --chown=metrics:metrics auth-metrics-seed.py .

EXPOSE 9099

USER metrics:metrics

CMD ["python", "auth-metrics-seed.py"]
