import 'dart:convert';

import 'package:cybervpn_mobile/features/config_import/data/parsers/vmess_parser.dart';
import 'package:cybervpn_mobile/features/config_import/domain/parsers/vpn_uri_parser.dart';
import 'package:flutter_test/flutter_test.dart';

/// Helper to encode a VMess JSON map into a vmess:// URI.
String _vmessUri(Map<String, dynamic> json) {
  final jsonString = jsonEncode(json);
  final encoded =
      base64Url.encode(utf8.encode(jsonString)).replaceAll('=', '');
  return 'vmess://$encoded';
}

/// Real-world VMess URI integration tests.
///
/// These simulate configs generated by popular panels (V2RayN, Clash,
/// Qv2ray, NekoBox) and subscription services. Focus is on realistic
/// JSON payloads with varying optional fields and transport modes.
void main() {
  late VmessParser parser;

  setUp(() {
    parser = VmessParser();
  });

  // ---------------------------------------------------------------------------
  // Real-world WS + TLS (most common VMess config)
  // ---------------------------------------------------------------------------
  group('VMess - real-world WS + TLS configs', () {
    test('V2RayN-style WS+TLS with CDN', () {
      final uri = _vmessUri({
        'v': '2',
        'ps': 'US-CloudFlare-WS',
        'add': 'cf-cdn.example.com',
        'port': 443,
        'id': '27848739-7e62-4138-9fd3-098a63964b6b',
        'aid': 0,
        'scy': 'auto',
        'net': 'ws',
        'type': 'none',
        'host': 'user-ws.workers.dev',
        'path': '/vmess-ws',
        'tls': 'tls',
        'sni': 'user-ws.workers.dev',
        'alpn': '',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.protocol, 'vmess');
      expect(config.serverAddress, 'cf-cdn.example.com');
      expect(config.port, 443);
      expect(config.uuid, '27848739-7e62-4138-9fd3-098a63964b6b');
      expect(config.remark, 'US-CloudFlare-WS');
      expect(config.transportSettings!['network'], 'ws');
      expect(config.transportSettings!['host'], 'user-ws.workers.dev');
      expect(config.transportSettings!['path'], '/vmess-ws');
      expect(config.tlsSettings!['security'], 'tls');
      expect(config.tlsSettings!['sni'], 'user-ws.workers.dev');
      expect(config.additionalParams!['alterId'], 0);
      expect(config.additionalParams!['version'], '2');
    });

    test('WS+TLS on non-standard port 8443', () {
      final uri = _vmessUri({
        'v': '2',
        'ps': 'JP-Tokyo-8443',
        'add': 'jp1.vpnservice.io',
        'port': '8443',
        'id': 'a3482e88-686a-4a58-8126-99c9034e4b09',
        'aid': '0',
        'net': 'ws',
        'type': 'none',
        'host': 'jp-cdn.vpnservice.io',
        'path': '/v2ray-ws',
        'tls': 'tls',
        'sni': 'jp-cdn.vpnservice.io',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      // port as string should be parsed to int
      expect(config.port, 8443);
      // aid as string should be parsed to int
      expect(config.additionalParams!['alterId'], 0);
    });

    test('WS without TLS (plain HTTP port 80)', () {
      final uri = _vmessUri({
        'v': '2',
        'ps': 'NoTLS-WS',
        'add': 'plain.example.com',
        'port': 80,
        'id': 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
        'aid': 0,
        'net': 'ws',
        'type': 'none',
        'host': 'plain.example.com',
        'path': '/free',
        'tls': '',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.port, 80);
      expect(config.tlsSettings, isNull);
      expect(config.transportSettings!['network'], 'ws');
    });
  });

  // ---------------------------------------------------------------------------
  // Real-world TCP configs
  // ---------------------------------------------------------------------------
  group('VMess - real-world TCP configs', () {
    test('TCP with TLS and HTTP header obfuscation', () {
      final uri = _vmessUri({
        'v': '2',
        'ps': 'DE-TCP-TLS',
        'add': '95.216.100.50',
        'port': 443,
        'id': 'c0293ea3-41b2-4e8c-b5f3-0a72d2ff1c82',
        'aid': 0,
        'net': 'tcp',
        'type': 'http',
        'host': 'www.amazon.de',
        'path': '/',
        'tls': 'tls',
        'sni': 'www.amazon.de',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.serverAddress, '95.216.100.50');
      expect(config.transportSettings!['network'], 'tcp');
      expect(config.transportSettings!['headerType'], 'http');
      expect(config.transportSettings!['host'], 'www.amazon.de');
      expect(config.tlsSettings!['security'], 'tls');
    });

    test('Bare TCP without TLS (minimal config)', () {
      final uri = _vmessUri({
        'add': '192.168.1.1',
        'port': 10086,
        'id': 'd9428888-6728-4c5a-8d49-5b4010bb2983',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.serverAddress, '192.168.1.1');
      expect(config.port, 10086);
      expect(config.remark, isNull);
      expect(config.transportSettings!['network'], 'tcp');
      expect(config.tlsSettings, isNull);
    });
  });

  // ---------------------------------------------------------------------------
  // Real-world gRPC configs
  // ---------------------------------------------------------------------------
  group('VMess - real-world gRPC configs', () {
    test('gRPC gun mode with TLS', () {
      final uri = _vmessUri({
        'v': '2',
        'ps': 'NL-gRPC-Gun',
        'add': 'grpc.example.nl',
        'port': 443,
        'id': 'e4d909c2-90d0-fb47-c9f1-0cb876843c8b',
        'aid': 0,
        'net': 'grpc',
        'type': 'gun',
        'path': 'vmess-grpc-service',
        'tls': 'tls',
        'sni': 'grpc.example.nl',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.transportSettings!['network'], 'grpc');
      expect(config.transportSettings!['headerType'], 'gun');
      expect(config.transportSettings!['path'], 'vmess-grpc-service');
      expect(config.remark, 'NL-gRPC-Gun');
    });
  });

  // ---------------------------------------------------------------------------
  // Real-world H2 and KCP configs
  // ---------------------------------------------------------------------------
  group('VMess - real-world H2 and KCP configs', () {
    test('H2 transport with TLS', () {
      final uri = _vmessUri({
        'v': '2',
        'ps': 'SG-H2-Server',
        'add': 'sg-node.example.com',
        'port': 443,
        'id': '7c9e6679-7425-40de-944b-e07fc1f90ae7',
        'aid': 0,
        'net': 'h2',
        'type': 'none',
        'host': 'sg-node.example.com',
        'path': '/h2',
        'tls': 'tls',
        'sni': 'sg-node.example.com',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.transportSettings!['network'], 'h2');
      expect(config.transportSettings!['path'], '/h2');
    });

    test('KCP with wechat-video header type', () {
      final uri = _vmessUri({
        'v': '2',
        'ps': 'CN-KCP-WeChat',
        'add': '103.152.35.2',
        'port': 29000,
        'id': '550e8400-e29b-41d4-a716-446655440000',
        'aid': 0,
        'net': 'kcp',
        'type': 'wechat-video',
        'tls': '',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.transportSettings!['network'], 'kcp');
      expect(config.transportSettings!['headerType'], 'wechat-video');
      expect(config.port, 29000);
    });

    test('KCP with SRTP header type', () {
      final uri = _vmessUri({
        'v': '2',
        'ps': 'KCP-SRTP',
        'add': '10.0.0.1',
        'port': 50000,
        'id': '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
        'aid': 0,
        'net': 'kcp',
        'type': 'srtp',
        'tls': '',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.transportSettings!['headerType'], 'srtp');
    });
  });

  // ---------------------------------------------------------------------------
  // Non-standard key aliases (seen in third-party clients)
  // ---------------------------------------------------------------------------
  group('VMess - non-standard JSON keys from third-party clients', () {
    test('NekoBox-style with "address" and "uuid" keys', () {
      final uri = _vmessUri({
        'v': '2',
        'remarks': 'NekoBox-Config',
        'address': 'neko.example.com',
        'server_port': 443,
        'uuid': 'aabbccdd-1122-3344-5566-778899001122',
        'alter_id': 0,
        'network': 'ws',
        'header_type': 'none',
        'request_host': 'cdn.neko.com',
        'obfs_param': '/neko-ws',
        'security': 'tls',
        'server_name': 'cdn.neko.com',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.serverAddress, 'neko.example.com');
      expect(config.uuid, 'aabbccdd-1122-3344-5566-778899001122');
      expect(config.remark, 'NekoBox-Config');
      expect(config.transportSettings!['network'], 'ws');
      expect(config.transportSettings!['host'], 'cdn.neko.com');
      expect(config.transportSettings!['path'], '/neko-ws');
      expect(config.tlsSettings!['sni'], 'cdn.neko.com');
    });

    test('Clash-style with "server" key', () {
      final uri = _vmessUri({
        'v': '2',
        'name': 'Clash-Node',
        'server': 'clash-node.example.com',
        'port': 443,
        'id': '12345678-1234-1234-1234-123456789012',
        'aid': 0,
        'transport': 'ws',
        'tls': 'tls',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.serverAddress, 'clash-node.example.com');
      expect(config.remark, 'Clash-Node');
      expect(config.transportSettings!['network'], 'ws');
    });
  });

  // ---------------------------------------------------------------------------
  // Invalid / malformed VMess URIs
  // ---------------------------------------------------------------------------
  group('VMess - real-world error scenarios', () {
    test('corrupted base64 from truncated subscription', () {
      // Simulates a subscription link that was truncated during download
      const uri = 'vmess://eyJ2IjoiMiIsInBzIjoiVVMtU2VydmVyIiwiYWRkIjoiZXhh';

      final result = parser.parse(uri);

      // Should fail gracefully (truncated base64/JSON)
      expect(result, isA<ParseFailure>());
    });

    test('valid base64 but JSON missing required address field', () {
      final uri = _vmessUri({
        'v': '2',
        'ps': 'Broken Config',
        'port': 443,
        'id': 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseFailure>());
      expect(
        (result as ParseFailure).message,
        contains('address'),
      );
    });

    test('valid base64 but JSON missing required id field', () {
      final uri = _vmessUri({
        'v': '2',
        'add': 'example.com',
        'port': 443,
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseFailure>());
      expect(
        (result as ParseFailure).message,
        contains('user ID'),
      );
    });

    test('base64 of a JSON array (not object)', () {
      final encoded = base64Url
          .encode(utf8.encode('["not", "an", "object"]'))
          .replaceAll('=', '');
      final uri = 'vmess://$encoded';

      final result = parser.parse(uri);

      expect(result, isA<ParseFailure>());
      expect(
        (result as ParseFailure).message,
        contains('must be an object'),
      );
    });

    test('base64 of plain text (not JSON)', () {
      final encoded = base64Url
          .encode(utf8.encode('This is not JSON at all'))
          .replaceAll('=', '');
      final uri = 'vmess://$encoded';

      final result = parser.parse(uri);

      expect(result, isA<ParseFailure>());
      expect(
        (result as ParseFailure).message,
        contains('JSON'),
      );
    });
  });

  // ---------------------------------------------------------------------------
  // Cross-field consistency checks
  // ---------------------------------------------------------------------------
  group('VMess - cross-field consistency', () {
    test('all parsed configs have protocol set to vmess', () {
      final configs = <Map<String, dynamic>>[
        {
          'add': 'a.com',
          'port': 443,
          'id': '12345678-1234-1234-1234-123456789012',
        },
        {
          'add': 'b.com',
          'port': 80,
          'id': '12345678-1234-1234-1234-123456789012',
          'net': 'ws',
          'tls': 'tls',
        },
        {
          'add': 'c.com',
          'port': 443,
          'id': '12345678-1234-1234-1234-123456789012',
          'net': 'grpc',
          'type': 'gun',
        },
      ];

      for (final json in configs) {
        final uri = _vmessUri(json);
        final result = parser.parse(uri);
        expect(result, isA<ParseSuccess>(), reason: 'Failed for: $json');
        final config = (result as ParseSuccess).config;
        expect(config.protocol, 'vmess');
      }
    });

    test('alterId defaults to 0 when not specified', () {
      final uri = _vmessUri({
        'add': 'example.com',
        'port': 443,
        'id': '12345678-1234-1234-1234-123456789012',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.additionalParams!['alterId'], 0);
    });

    test('high alterId values (legacy VMess configs)', () {
      final uri = _vmessUri({
        'add': 'legacy.example.com',
        'port': 443,
        'id': '12345678-1234-1234-1234-123456789012',
        'aid': 64,
        'net': 'tcp',
        'tls': '',
      });

      final result = parser.parse(uri);

      expect(result, isA<ParseSuccess>());
      final config = (result as ParseSuccess).config;
      expect(config.additionalParams!['alterId'], 64);
    });
  });
}
